config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'urls#index'
  resources :urls

  get '/urls/:id/short' => 'urls#short'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
	validates :long_url, presence: true
	validates :long_url, format: { with: URI.regexp }, allow_blank: true
	validates :short_url, uniqueness: true

	def shorten
		self.short_url = rand(36**7).to_s(36)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	def index
		@urls = Url.all
		@url = Url.new
	end

	def new
		@url = Url.new
	end

	def create
		@url = Url.new(url_params)
		@url.shorten
		if @url.save
			# redirect_to @url
			respond_to do |format|
				format.html { redirect_to @url }
				format.js
			end
		else
			render 'new'
		end
	end

	def show
		@url = Url.find(params[:id])
	end

	def destroy
		@url = Url.find(params[:id])
		@url.destroy
		redirect_to urls_path
	end

	def short
		url = Url.find(params[:id])
		redirect_to url.long_url
	end

	private

	def url_params
		params.require(:url).permit(:long_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url, remote: true do |f| %>
	<p>
		<%= f.label "Type your URL here:" %><br>
		<%= f.text_field :long_url %>
	</p>

	<p>
		<%= f.submit "Shorten URL!"%>
	</p>
<% end %>

app/views/urls/_url.html.erb
<!-- Thanks to https://stackoverflow.com/questions/21852974/add-row-to-table-with-jquery-and-rails -->
<tr>
	<td><a href = <%= @url.long_url %> ><%= @url.long_url%></a></td>
	<td><%= link_to @url.short_url, controller: :urls, action: :short, id: url %></td>
	<td><%= link_to 'Show', url_path(@url) %></td>
	<td><%= link_to 'Delete', url_path(@url), method: :delete, data: { confirm: 'Are you sure?' }%></td>
</tr>

app/views/urls/create.js.erb
$('table').append('<%= j render(@url) %>');

app/views/urls/index.html.erb
<%#= link_to "Shorten a Url!", new_url_path %>
<%= render 'form' %>

<table>
	<tr>
		<th>Original URL</th>
		<th>Shortened URL</th>
	</tr>

	<% @urls.each do |url| %>
		<tr>
			<td><a href = <%= url.long_url %> ><%= url.long_url%></a></td>
			<td><%= link_to url.short_url, controller: :urls, action: :short, id: url %></td>
			<td><%= link_to 'Show', url_path(url) %></td>
			<td><%= link_to 'Delete', url_path(url), method: :delete, data: { confirm: 'Are you sure?' }%></td>
		</tr>
	<% end %>
</table>

app/views/urls/new.html.erb
<h3>This is urls/new</h3>
<%= render 'form' %>
<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<h3>This is urls/show</h3>
	<p><%= @url.long_url %></p>
	<p><%= @url.short_url %></p>
	<%= link_to 'Back', urls_path %>
	<%#= link_to 'Back', controller: :urls, action: :index %>